### PR TITLE
fix(app): Do not override existing moz:firefoxOptions

### PR DESCRIPTION
**Pull request by Tallyb**

### CODE REVIEW

**Comment by Tallyb** [comment]
As with other PR, I have trouble running the tests. I get green 0 passing.

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
Let's make sure we have this also ported to [v5](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-firefox-profile-service) before we merge and release it.

**Comment by Tallyb** [comment]
https://github.com/webdriverio/webdriverio/pull/2957

**Comment by christian-bromann** [comment]
released with `v0.1.3`

**Pull request merged**
