### PR TITLE
Set profile in newer firefox/geckodriver versions

### LINKED ISSUE #12: Fails to set profile in newer Firefox/Geckodriver versions
The profile defined in wdio.conf is not set in newer versions of firefox and geckodriver

Firefox: 56.0
geckodriver: 0.19.0
selenium-server-standalone: 3.6.0

According to https://github.com/saadtazi/firefox-profile-js/issues/95 the browser capabilities changed and the profile should be set like so: 

```
cap['moz:firefoxOptions'] = {
	profile: zippedProfile
};
```

Instead of the old definition

```
cap.firefox_profile = zippedProfile;
```

### PR DESCRIPTION
**Pull request by dombre**
Fixes #12

### CODE REVIEW

**Comment by dombre** [comment]
I messed up the original pull request (I have committed with the wrong username and wasn't able to sign the CLA). 

So here is my second try.

**Comment by rbardini** [comment]
What is the status here? #12 was closed but the fix hasn't been merged yet.

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@rbardini thanks for reminding. Released as wdio-firefox-profile-service 0.1.1

**Pull request merged**
